site_name: K-Energy
repo_url: https://github.com/Darin-Group
repo_name: Darin-Group/K-Energy-Docs
site_author: K-Energy
edit_uri: K-Energy-Docs/edit/master/docs/
site_description: >-
  Fuel Distribution System
copyright: Copyright &copy; 2023 K-Energy
default: getting-started
theme:
  name: material
  custom_dir: docs/overrides
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
nav:
    - Home: 'index.md'
    - Identity: 
        - Start:            'identity/start.md'
        - Apps & Scopes:    'identity/apps-and-scopes.md'
        - Access Trees:     'identity/access-trees.md'
        - Users:            'identity/users.md'
    - Web App:
        - Start:        'web/start.md'
        - Contacts:     'web/contacts.md'
        - Products:     'web/products.md'
        - Storage:      'web/storage.md'
        - Purchases:    'web/purchases.md'
        - Sales:        'web/sales.md'
        - Lab:          'web/lab.md'
    - Mobile App: 
        - Start:           'mobile/start.md'
        - Purchase:        'mobile/purchase.md'
        - Sale:            'mobile/sale.md'
    - Tutorial:
        - Start:             'tutorial/start.md'
        - Contacts:          'tutorial/contacts.md'
        - Products:          'tutorial/products.md'
        - Storage:           'tutorial/storage.md'
        - Lab:               'tutorial/lab.md'
        - Purchase:          'tutorial/purchase.md'
        - Sale:              'tutorial/sale.md'
  
extra_css:
  - overrides/css/extra.css

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables
  - pymdownx.mark
  - toc:
      permalink: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg